#!/usr/bin/env bash
# Configures an Ubuntu server as follows:
#  -- localhost resolves to 127.0.0.2
#  -- facebook.com resolves to 8.8.8.8

# Create a new hosts file
cp /etc/hosts ~/hosts.new

# Add custom entries for localhost and facebook.com
echo "127.0.0.2    localhost" >> ~/hosts.new
echo "8.8.8.8      facebook.com" >> ~/hosts.new

# Replace the original hosts file with the new version
sudo cp -f ~/hosts.new /etc/hosts
